spring:
  application:
    name: mycar-market-backend
  config:
    import: optional:classpath:application-secret.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  profiles:
    active: prod

jwt:
  expiration: 86400000 # 1 day
